"""
ranker_trainer.py

Trains an XGBRanker to rank stocks within each date by their next-30-day
forward return.  Kept alongside trainer.py for A/B comparison.

Design
------
* Each unique date is a "query" (group) for the ranker.
* The relevance label for each (ticker, date) row is the rank percentile
  of its forward_return within that date, scaled to [0, 1000] and cast to
  int.  Higher label = stock had a better realized return.
* XGBRanker optimises NDCG so it learns the *ordering*, not a category.
* At inference, sort by predicted score within each date; take top-N.
  No probability threshold is needed.

Anti-bias guarantees
--------------------
* All chronological splits respect date boundaries — no date spans two splits.
* Group sizes are computed AFTER sorting by date (ascending) and verified with
  assert sum(groups) == len(df) before every fit() call.
* forward_return comes from the labels table which was generated by
  labeler.py using shift(-30) — the ONLY sanctioned negative shift.
"""

import logging
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from xgboost import XGBRanker

import backtest
import database
from encoders import SECTOR_ENCODER_PATH

# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Feature set — identical to trainer.py so both models are evaluated on the
# same inputs (fair A/B comparison).
# ---------------------------------------------------------------------------
FEATURE_COLS: list[str] = [
    # Momentum oscillators
    "rsi_14", "rsi_28",
    "stoch_k", "stoch_d",
    "williams_r",
    "roc_10",
    "macd_hist",
    # Volatility & bands
    "bb_width",
    "bb_pct_b",
    "atr_14",
    # Volume
    "volume_ratio",
    # Return series
    "return_1d",
    "return_5d",
    "return_20d",
    "volatility_20d",
    # Position features
    "pct_from_52w_high",
    "dist_from_sma50",
    # Regime
    "golden_cross",
    # Sector / size
    "sector_encoded",
    # Macro
    "fed_funds_rate",
    "treasury_10y",
    "yield_curve_spread",
    "vix",
    "vix_sma20",
    "vix_regime",
    "sp500_return_20d",
    "sp500_above_sma50",
    "unemployment_rate",
    "cpi_yoy",
    "spread_10y2y",
    # EDGAR
    "days_since_8k",
    "count_8k_90d",
    # Earnings
    "earnings_surprise_pct",
    "days_since_earnings",
    "earnings_beat",
    # Sentiment
    "sentiment_7d_avg",
    # Sector-relative
    "rsi_14_vs_sector",
    "return_5d_vs_sector",
    "return_20d_vs_sector",
    "macd_hist_vs_sector",
    "vol_20d_vs_sector",
    "dist_sma50_vs_sector",
]

MODEL_DIR   = Path(__file__).parent / "models"
RANKER_PATH = MODEL_DIR / "universal_ranker.joblib"


# ---------------------------------------------------------------------------

class UniversalRanker:
    """
    XGBRanker-based stock ranker for 30-day forward-return ranking.

    Usage
    -----
    >>> r = UniversalRanker()
    >>> r.fit()                      # trains on full DB, saves metrics
    >>> r.save()
    >>> r2 = UniversalRanker.load()
    >>> scores = r2.predict(feature_df)   # higher score = better rank
    >>> topk_df = r2.evaluate_topk(test_df, k=20)
    """

    def __init__(self) -> None:
        self.model:              XGBRanker | None = None
        self.feature_cols:       list[str]        = FEATURE_COLS
        self.split_dates:        dict             = {}
        self.metrics:            dict             = {}
        self.holdout_df:         pd.DataFrame | None = None
        self.feature_bounds:     dict | None      = None
        self.sector_encoder_path: str | None      = None

    # -----------------------------------------------------------------------
    # Data loading
    # -----------------------------------------------------------------------

    def load_data(self, tickers: list[str] | None = None) -> pd.DataFrame:
        """
        Load features joined with labels (forward_return only — no label
        column).  Computes rank_label (int 0..1000) per date in Python.

        Returns a DataFrame with columns:
            ticker, date, <FEATURE_COLS>, forward_return, rank_label
        sorted ascending by (ticker, date) after dropping the first 20 rows
        per ticker (unstabilized rolling indicators).
        """
        # ---- point-in-time fundamentals guard --------------------------------
        with database.connection() as conn:
            fund_cols = {
                row[1]
                for row in conn.execute("PRAGMA table_info(fundamental_metadata)")
            }
        _structural = {"ticker", "fetch_date", "is_point_in_time"}
        fund_cols -= _structural
        for col in self.feature_cols:
            if col in fund_cols:
                raise RuntimeError(
                    f"BIAS GUARD: fundamental column '{col}' found in FEATURE_COLS. "
                    "Remove it — yfinance fundamentals are not point-in-time."
                )
        # ----------------------------------------------------------------------

        feat_select = ", ".join(f"f.{c}" for c in FEATURE_COLS)
        base_sql = f"""
            SELECT f.ticker, f.date,
                   {feat_select},
                   l.forward_return
            FROM   features f
            JOIN   labels   l ON l.ticker = f.ticker AND l.date = f.date
        """
        with database.connection() as conn:
            if tickers:
                ph   = ",".join("?" * len(tickers))
                rows = conn.execute(
                    base_sql + f" WHERE f.ticker IN ({ph}) ORDER BY f.date, f.ticker",
                    tickers,
                ).fetchall()
            else:
                rows = conn.execute(
                    base_sql + " ORDER BY f.date, f.ticker"
                ).fetchall()

        df = pd.DataFrame([dict(r) for r in rows])
        log.info(
            "Loaded %d rows covering %d tickers  (%s to %s).",
            len(df), df["ticker"].nunique(),
            df["date"].min(), df["date"].max(),
        )

        # Drop the first 20 rows per ticker (unstabilized rolling windows)
        df = df.sort_values(["ticker", "date"])
        df = df[df.groupby("ticker").cumcount() >= 20].reset_index(drop=True)
        log.info("After masking first 20 rows per ticker: %d rows remain.", len(df))

        # Drop dates with only one ticker — NDCG undefined for a group of 1
        date_counts = df.groupby("date").size()
        valid_dates = date_counts[date_counts >= 2].index
        before = len(df)
        df = df[df["date"].isin(valid_dates)].reset_index(drop=True)
        dropped = before - len(df)
        if dropped:
            log.info("Dropped %d rows on single-ticker dates.", dropped)

        # ---- Rank-percentile label ----------------------------------------
        # rank(pct=True) gives values in (0, 1] where 1.0 = best performer.
        # Multiply by 1000 and cast to int → relevance scores in [1, 1000].
        # Higher label = stock had a higher forward return on that date.
        df["rank_label"] = (
            df.groupby("date")["forward_return"]
            .rank(ascending=True, pct=True, method="average")
            .mul(1000)
            .astype(int)
        )
        log.info(
            "rank_label range: [%d, %d]",
            int(df["rank_label"].min()), int(df["rank_label"].max()),
        )
        return df

    # -----------------------------------------------------------------------
    # Chronological split — NEVER random, always on date boundaries
    # -----------------------------------------------------------------------

    def chronological_split(
        self,
        df: pd.DataFrame,
        train_frac:   float = 0.70,
        val_frac:     float = 0.15,
        holdout_frac: float = 0.05,
    ) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        """
        Split on unique date boundaries so every row for a given date lands
        in exactly one partition.

        Timeline: [train 70%][val 15%][test 10%][holdout 5%]

        Holdout is carved from the very end and must NEVER be used for any
        tuning decision (thresholds, hyperparameters, features).
        """
        unique_dates = sorted(df["date"].unique())
        n = len(unique_dates)

        if holdout_frac > 0:
            holdout_start_idx  = int(n * (1.0 - holdout_frac))
            holdout_start_date = unique_dates[holdout_start_idx]
            working_dates      = unique_dates[:holdout_start_idx]
        else:
            holdout_start_date = None
            working_dates      = unique_dates

        nw = len(working_dates)
        total_non_holdout = 1.0 - holdout_frac if holdout_frac > 0 else 1.0
        eff_train = train_frac / total_non_holdout
        eff_val   = val_frac   / total_non_holdout

        train_end_date = working_dates[int(nw * eff_train) - 1]
        val_end_date   = working_dates[int(nw * (eff_train + eff_val)) - 1]

        train   = df[df["date"] <= train_end_date]
        val     = df[(df["date"] > train_end_date) & (df["date"] <= val_end_date)]
        test    = df[(df["date"] > val_end_date) & (
                      (df["date"] < holdout_start_date) if holdout_start_date else True
                  )]
        holdout = df[df["date"] >= holdout_start_date] if holdout_start_date else df.iloc[0:0]

        self.split_dates = {
            "train_end":  train_end_date,
            "val_end":    val_end_date,
            "test_start": test["date"].min() if len(test) else "",
            "test_end":   test["date"].max() if len(test) else "",
        }

        log.info(
            "Split — train: %d rows (up to %s) | "
            "val: %d rows (%s–%s) | "
            "test: %d rows (%s–%s)",
            len(train), train_end_date,
            len(val),   val["date"].min() if len(val) else "",  val_end_date,
            len(test),  test["date"].min() if len(test) else "", test["date"].max() if len(test) else "",
        )
        if holdout_start_date:
            log.info(
                "Holdout: %d rows (%s to %s) — DO NOT USE FOR ANY TUNING DECISION.",
                len(holdout),
                holdout["date"].min() if len(holdout) else "",
                holdout["date"].max() if len(holdout) else "",
            )
        return train, val, test, holdout

    # -----------------------------------------------------------------------
    # XGBRanker factory
    # -----------------------------------------------------------------------

    def _make_ranker(self) -> XGBRanker:
        """
        Depth=6 and lr=0.05 — lighter regularisation than the classifier
        because rank objectives are less prone to class-collapse overfitting.

        ndcg_exp_gain=False switches to linear DCG gain: gain(r) = r.
        This lifts the ≤31 label restriction that the default exponential
        gain function imposes, letting us use the full [0, 1000] label range.
        """
        return XGBRanker(
            objective             = "rank:ndcg",
            ndcg_exp_gain         = False,   # linear DCG gain — labels can exceed 31
            tree_method           = "hist",
            n_estimators          = 1000,
            max_depth             = 6,
            learning_rate         = 0.05,
            reg_alpha             = 0.5,
            reg_lambda            = 1.0,
            min_child_weight      = 10,
            subsample             = 0.8,
            colsample_bytree      = 0.8,
            n_jobs                = -1,
            eval_metric           = "ndcg@50",
            early_stopping_rounds = 50,
            random_state          = 42,
            verbosity             = 0,
        )

    # -----------------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------------

    def _Xy(self, df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
        X = df[self.feature_cols].values.astype(float)
        y = df["rank_label"].values.astype(float)
        return X, y

    def _groups(self, df: pd.DataFrame, label: str = "") -> list[int]:
        """
        Compute XGBRanker group sizes from a date-sorted DataFrame.

        df MUST already be sorted by date (ascending) so that the group
        sizes align with the row order.  The assertion verifies this
        invariant before any fit() call.
        """
        sizes = df.groupby("date", sort=False).size().tolist()
        assert sum(sizes) == len(df), (
            f"{'[' + label + '] ' if label else ''}Group size mismatch: "
            f"sum({len(sizes)} groups)={sum(sizes)} != len(df)={len(df)}"
        )
        return sizes

    def _print_feature_importances(self) -> None:
        if self.model is None:
            return
        pairs = sorted(
            zip(self.feature_cols, self.model.feature_importances_),
            key=lambda x: x[1], reverse=True,
        )
        log.info("Top 10 feature importances (ranker):")
        for rank, (feat, imp) in enumerate(pairs[:10], 1):
            bar = "#" * int(imp * 200)
            log.info("  %2d. %-28s  %.4f  %s", rank, feat, imp, bar)

    # -----------------------------------------------------------------------
    # Training
    # -----------------------------------------------------------------------

    def fit(
        self,
        df: pd.DataFrame | None = None,
        tickers: list[str] | None = None,
    ) -> "UniversalRanker":
        """
        Full pipeline: load → split → sort → build groups → fit → evaluate.

        Each split is sorted by (date, ticker) before group sizes are
        computed so the groups align with row order — required by XGBRanker.
        """
        if df is None:
            df = self.load_data(tickers)

        train_df, val_df, test_df, holdout_df = self.chronological_split(df)
        self.holdout_df = holdout_df

        # Sort each split by (date, ticker) — required for contiguous groups
        train_df = train_df.sort_values(["date", "ticker"]).reset_index(drop=True)
        val_df   = val_df.sort_values(["date", "ticker"]).reset_index(drop=True)
        test_df  = test_df.sort_values(["date", "ticker"]).reset_index(drop=True)

        train_groups = self._groups(train_df, "train")
        val_groups   = self._groups(val_df,   "val")

        X_train, y_train = self._Xy(train_df)
        X_val,   y_val   = self._Xy(val_df)

        log.info(
            "Fitting XGBRanker — train: %d rows (%d dates) | val: %d rows (%d dates)",
            len(X_train), len(train_groups),
            len(X_val),   len(val_groups),
        )

        self.model = self._make_ranker()
        self.model.fit(
            X_train, y_train,
            group     = train_groups,
            eval_set  = [(X_val, y_val)],
            eval_group = [val_groups],
            verbose   = False,
        )

        log.info(
            "Best iteration: %d  |  best val %s",
            self.model.best_iteration,
            self.model.best_score,
        )

        # Feature bounds (for prediction_guard compatibility)
        self.feature_bounds = {
            col: (float(train_df[col].min()), float(train_df[col].max()))
            for col in self.feature_cols
        }

        self._print_feature_importances()

        # ---- Evaluate on test set ------------------------------------------
        log.info("=== Test-set evaluation ===")
        if len(test_df) > 0:
            topk_df = self.evaluate_topk(test_df, k=20)
            if not topk_df.empty:
                self.metrics.update({
                    "test_mean_edge":   float(topk_df["edge"].mean()),
                    "test_mean_topk":   float(topk_df["topk_return"].mean()),
                    "test_mean_bah":    float(topk_df["bah_return"].mean()),
                    "test_dates":       len(topk_df),
                    "best_iteration":   self.model.best_iteration,
                })
        else:
            log.warning("test_df is empty — skipping evaluation.")

        return self

    # -----------------------------------------------------------------------
    # Inference
    # -----------------------------------------------------------------------

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        """
        Return raw relevance scores for each row.

        Higher score = model believes this stock will rank higher within
        its date.  Sort descending within each date to get the top-N picks.
        """
        if self.model is None:
            raise RuntimeError("Model not trained — call fit() first.")
        return self.model.predict(df[self.feature_cols].values.astype(float))

    # -----------------------------------------------------------------------
    # Evaluation
    # -----------------------------------------------------------------------

    def evaluate_topk(
        self,
        df: pd.DataFrame,
        k: int = 20,
    ) -> pd.DataFrame:
        """
        For each date in *df*, predict scores, take the top-k stocks by
        score, and compute their mean forward_return vs buy-and-hold.

        Also calls backtest.run() with the aggregated stats so the viability
        verdict is printed using the same thresholds as the classifier.

        Parameters
        ----------
        df : DataFrame with columns from FEATURE_COLS + 'forward_return'.
        k  : Number of top stocks to select per date.

        Returns
        -------
        DataFrame indexed by date with columns:
            topk_return, bah_return, edge, n_stocks
        """
        if self.model is None:
            raise RuntimeError("Model not trained — call fit() first.")

        df = df.sort_values(["date", "ticker"]).reset_index(drop=True)
        scores       = self.predict(df)
        df           = df.copy()
        df["_score"] = scores

        buy_by_date: dict = {}
        all_by_date: dict = {}
        rows: list[dict]  = []

        for date, grp in df.groupby("date", sort=True):
            fwd      = grp["forward_return"].values.astype(float)
            sc       = grp["_score"].values.astype(float)
            actual_k = min(k, len(grp))
            # argsort ascending → reverse → take first actual_k = top-k by score
            top_idx  = np.argsort(sc)[::-1][:actual_k]

            topk_ret = float(np.mean(fwd[top_idx]))
            bah_ret  = float(np.mean(fwd))

            buy_by_date[date] = fwd[top_idx].tolist()
            all_by_date[date] = fwd.tolist()

            rows.append({
                "date":        date,
                "topk_return": topk_ret,
                "bah_return":  bah_ret,
                "edge":        topk_ret - bah_ret,
                "n_stocks":    len(grp),
            })

        result_df = pd.DataFrame(rows).set_index("date") if rows else pd.DataFrame()

        if not result_df.empty:
            log.info(
                "evaluate_topk(k=%d): %d dates | "
                "mean edge=%+.2f%% | topk=%+.2f%% | bah=%+.2f%%",
                k, len(result_df),
                result_df["edge"].mean() * 100,
                result_df["topk_return"].mean() * 100,
                result_df["bah_return"].mean() * 100,
            )

            buy_edge_gross = float(result_df["topk_return"].mean())
            bah_return_agg = float(result_df["bah_return"].mean())

            backtest.run({
                "buy_edge_gross":      buy_edge_gross,
                "bah_return":          bah_return_agg,
                "buy_returns_by_date": buy_by_date,
                "all_returns_by_date": all_by_date,
            })

        return result_df

    # -----------------------------------------------------------------------
    # Persistence
    # -----------------------------------------------------------------------

    def save(self, path: Path | str | None = None) -> Path:
        """Save ranker + metadata with joblib."""
        save_path = Path(path) if path else RANKER_PATH
        save_path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(
            {
                "model":               self.model,
                "feature_cols":        self.feature_cols,
                "split_dates":         self.split_dates,
                "metrics":             self.metrics,
                "feature_bounds":      self.feature_bounds,
                "sector_encoder_path": str(SECTOR_ENCODER_PATH),
            },
            save_path,
        )
        log.info("Saved → %s", save_path)
        return save_path

    @classmethod
    def load(cls, path: Path | str | None = None) -> "UniversalRanker":
        """Load a previously saved ranker."""
        load_path = Path(path) if path else RANKER_PATH
        if not load_path.exists():
            raise FileNotFoundError(f"No ranker file at {load_path}")
        payload = joblib.load(load_path)
        inst                     = cls()
        inst.model               = payload["model"]
        inst.feature_cols        = payload["feature_cols"]
        inst.split_dates         = payload.get("split_dates", {})
        inst.metrics             = payload.get("metrics", {})
        inst.feature_bounds      = payload.get("feature_bounds")
        inst.sector_encoder_path = payload.get("sector_encoder_path")
        log.info("Loaded ← %s", load_path)
        return inst


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    _tickers = sys.argv[1:] if len(sys.argv) > 1 else None
    ranker   = UniversalRanker()
    ranker.fit(tickers=_tickers)
    ranker.save()
